#!/bin/bash


# Install coursier

curl -L -o coursier https://git.io/coursier-cli
chmod +x coursier

./coursier launch --fork almond:0.13.1 --scala 3.1.1 -- --install


jupyter labextension install --minimize=False \
  jupyterlab-plotly \
  @almond-sh/scalafmt \
  @almond-sh/jupyterlab_variableinspector