#!/bin/bash


# Install coursier

curl -L -o coursier https://git.io/coursier-cli
chmod +x coursier

./coursier launch --fork almond -- --install

# jupyter labextension install --minimize=False \
#   @almond-sh/scalafmt \
#   @almond-sh/jupyterlab_variableinspector